pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'echo "am building the docker"'
            }
        }
        
        stage('Deploy'){
            steps{
                sh 'echo "am deploying the image in docker and editing this line"'
            }
        }
        stage('Relese'){
            steps{
                sh 'echo "Relesing the build"'
            }
        }
    }
}